{% set name = "dill" %}
{% set version = "2.4.1" %}
{% set build = 0 %}
{% set sha256 =  "93c9e3c8e24ab91786639273a89934c2f384638b03aa0dd0f40e58cdf5a8f0f7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GTkorvo/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    strong:
      - dill

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - make          # [unix]
    - pkg-config    # [unix]
    - cmake >=3.11
  run:


test:
  imports:
  commands:
    - test -f ${PREFIX}/lib/cmake/dill/dill-config.cmake                      # [unix]
    - test -f ${PREFIX}/lib/libdill.so                                          # [linux]
    - otool -L ${PREFIX}/lib/libdill.dylib                                      # [osx]
    - if exist %LIBRARY_PREFIX%\bin\dill.dll (exit 0) else (exit 1)             # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\dill\dill-config.cmake (exit 0) else (exit 1)  # [win]
